### ISSUE TITLE
autoOrient triggered too early

### ISSUE THREAD

**Issue by malvese** [madergrafisch/kirby-imageconverter#1]
It seems when autoOrient is set to true, the rotation happens before the image is resized. The result is images with the right orientation, but the wrong dimensions.
Inverting the `-resize`and `-auto-orient`commands around lines 86-90 solves the issue, but it should be tested a bit more.

Please see this thread for more details and context: http://forum.getkirby.com/t/wrong-orientation-of-images-portrait-landscape-after-upload/692/19

**Comment by seehat** [comment]
Thx for the info. 

This is fixed in the new plugin repo: https://github.com/madergrafisch/kirby-plugins/tree/master/imageconverter

**Comment by malvese** [comment]
:+1:
